package websiteBuilder;
// Generated Jun 6, 2017 11:32:15 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Website generated by hbm2java
 */
@Entity
@Table(name="website"
    ,catalog="websitebuilder"
)
public class Website  implements java.io.Serializable {


     private int userId;
     private String url;
     private Boolean published;
     private String websiteName;

    public Website() {
    }

	
    public Website(int userId) {
        this.userId = userId;
    }
    public Website(int userId, String url, Boolean published, String websiteName) {
       this.userId = userId;
       this.url = url;
       this.published = published;
       this.websiteName = websiteName;
    }
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="url", length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="published")
    public Boolean getPublished() {
        return this.published;
    }
    
    public void setPublished(Boolean published) {
        this.published = published;
    }

    
    @Column(name="website_name", length=25)
    public String getWebsiteName() {
        return this.websiteName;
    }
    
    public void setWebsiteName(String websiteName) {
        this.websiteName = websiteName;
    }




}


